name: Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'

jobs:
  lock:
    name: Create lockfiles
    runs-on: ubuntu-24.04
    steps:
      - name: Configure
        run: |
          apt-get update && apt-get install -y python3 python3-pip
          python3 -m pip install conan
          conan config install https://github.com/theo-dep-bo/conanci_conf.git
          conan profile detect
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create lockfile
        run: |
          conan remote enable develop
          conan remote login develop "${{ secrets.USERDEVELOP }}" -p "${{ secrets.TOKENDEVELOP }}"
          conan lock create . -pr=windows --lockfile-out=conan.lock
          conan lock create . -pr=linux  --lockfile=conan.lock --lockfile-out=conan.lock
      - name: Upload lockfile
        uses: actions/upload-artifact@v4
        with:
          name: conan.lock
          path: conan.lock

  linux:
    uses: ./.github/workflows/linux.yml
    name: Linux
    needs: [lock]
    secrets:
      USERDEVELOP: ${{ secrets.USERDEVELOP }}
      TOKENDEVELOP: ${{ secrets.TOKENDEVELOP }}
      USERPACKAGES: ${{ secrets.USERPACKAGES }}
      TOKENPACKAGES: ${{ secrets.TOKENPACKAGES }}

  windows:
    uses: ./.github/workflows/windows.yml
    name: Windows
    needs: [lock]
    secrets:
      USERDEVELOP: ${{ secrets.USERDEVELOP }}
      TOKENDEVELOP: ${{ secrets.TOKENDEVELOP }}
      USERPACKAGES: ${{ secrets.USERPACKAGES }}
      TOKENPACKAGES: ${{ secrets.TOKENPACKAGES }}

  promotion:
    runs-on: ubuntu-24.04
    needs: [linux, windows]
    steps:
      - name: Configure environment and install Conan release
        run: |
          apt-get update && apt-get install -y python3 python3-pip
          python3 -m pip install conan
          conan config install https://github.com/theo-dep-bo/conanci_conf.git
      - name: Configure repos
        run: |
          conan remote enable packages
          conan remote login packages "${{ secrets.USERPACKAGES }}" -p "${{ secrets.TOKENPACKAGES }}"
          conan remote enable products
          conan remote login products "${{ secrets.USERPRODUCTS }}" -p "${{ secrets.TOKENPRODUCTS }}"
      - name: Download pkglists
        uses: actions/download-artifact@v4
        with:
          path: .
          pattern: uploaded_*.json
          merge-multiple: true
      - name: Display structure of downloaded files
        run: ls -R
      - name: promote packages
        run: |
          conan pkglist merge -l uploaded_windows.json -l uploaded_linux.json --format=json > uploaded.json
          conan download --list=uploaded.json -r=packages --format=json > promote.json
          conan upload --list=promote.json -r=products -c
