name: Windows build

on:
  workflow_call:
    secrets:
      USERDEVELOP:
        required: true
      TOKENDEVELOP:
        required: true
      USERPACKAGES:
        required: true
      TOKENPACKAGES:
        required: true

jobs:
  windows_build:
    runs-on: windows-2022
    name: Build Windows package
    steps:
      - name: Configure environment and install Conan release
        run: python3 -m pip install conan
      - name: Configure repos
        run: |
          conan profile detect
          conan config install https://github.com/theo-dep-bo/conanci_conf.git
          conan remote enable develop
          conan remote login develop "${{ secrets.USERDEVELOP }}" -p "${{ secrets.TOKENDEVELOP }}"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download conan.lock
        uses: actions/download-artifact@v4
        with:
          name: conan.lock
      - name: build package
        run: |
          conan create . --build="missing:mathlib/*" -pr=windows --lockfile=conan.lock --format=json > graph.json
      - name: upload package
        shell: cmd
        run: |
          conan remote enable packages
          conan remote login packages "${{ secrets.USERPACKAGES }}" -p "${{ secrets.TOKENPACKAGES }}"
          conan list --graph=graph.json --graph-binaries=build --format=json > built.json
          conan upload -l=built.json -r=packages --confirm --format=json > uploaded_windows.json
      - name: 'Upload pkglist'
        uses: actions/upload-artifact@v4
        with:
          name: uploaded_windows.json
          path: uploaded_windows.json
